### ISSUE TITLE
Can't run subapp-poc

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode#1510]
## Type of issue

**Bug**

The [samples/poc-subapp](https://github.com/electrode-io/electrode/tree/master/samples/poc-subapp) won't run due to Webpack errors.

## My environment

* *OS version/details*: `macOS 10.15.3`
* *Node version:* `10.17.0`
* *npm version:* `6.11.3`
* *Version of yo :* n/a

## Expected behavior

The poc-subapp should run.

## Current behavior

The poc-subapp won't build due to a Webpack error.

## Steps to reproduce the behavior

1. Run `fyn install` in the repository
2. `cd samples/poc-subapp && fyn install`
3. `fyn run dev`
4. Observe Webpack errors

## Command line output

From http://localhost:2992/__electrode_dev/reporter:

```

ERROR in ../node_modules/subapp-react/lib/index.js
Module not found: Error: Can't resolve '../dist/node/app-context' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-react/lib'
 @ ../node_modules/subapp-react/lib/index.js 6:32-67
 @ ./02.main-body/main-body.jsx
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-react/lib/framework-lib.js
Module not found: Error: Can't resolve '../dist/node/app-context' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-react/lib'
 @ ../node_modules/subapp-react/lib/framework-lib.js 10:32-67
 @ ../node_modules/subapp-react/lib/index.js
 @ ./02.main-body/main-body.jsx
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-web/lib/index.js
Module not found: Error: Can't resolve '../dist/node/make-subapp-spec' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-web/lib'
 @ ../node_modules/subapp-web/lib/index.js 7:36-76
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-redux/lib/index.js
Module not found: Error: Can't resolve '../dist/node/shared' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-redux/lib'
 @ ../node_modules/subapp-redux/lib/index.js 5:15-45
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/filter-scan-dir/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/filter-scan-dir/lib'
 @ ../node_modules/filter-scan-dir/lib/index.js 5:11-24
 @ ../node_modules/subapp-util/lib/index.js
 @ ../node_modules/subapp-redux/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/request/lib'
 @ ../node_modules/request/lib/har.js 3:9-22
 @ ../node_modules/request/request.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-web/lib/init.js
Module not found: Error: Can't resolve 'fs' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-web/lib'
 @ ../node_modules/subapp-web/lib/init.js 5:11-24
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-web/lib/load.js
Module not found: Error: Can't resolve 'fs' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-web/lib'
 @ ../node_modules/subapp-web/lib/load.js 15:11-24
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/subapp-web/lib/util.js
Module not found: Error: Can't resolve 'fs' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/subapp-web/lib'
 @ ../node_modules/subapp-web/lib/util.js 5:11-24
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/forever-agent'
 @ ../node_modules/forever-agent/index.js 6:10-24
 @ ../node_modules/request/request.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/tough-cookie/lib'
 @ ../node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ../node_modules/request/lib/cookies.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/tunnel-agent'
 @ ../node_modules/tunnel-agent/index.js 3:10-24
 @ ../node_modules/request/lib/tunnel.js
 @ ../node_modules/request/request.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/forever-agent'
 @ ../node_modules/forever-agent/index.js 7:10-24
 @ ../node_modules/request/request.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js

ERROR in ../node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/dudeman/electrode-io/electrode/samples/poc-subapp/node_modules/tunnel-agent'
 @ ../node_modules/tunnel-agent/index.js 4:10-24
 @ ../node_modules/request/lib/tunnel.js
 @ ../node_modules/request/request.js
 @ ../node_modules/request/index.js
 @ ../node_modules/subapp-web/lib/load.js
 @ ../node_modules/subapp-web/lib/index.js
 @ ./.__dev_hmr/hmr-02.main-body.js
 @ multi webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A2992%2F__webpack_hmr ./.__dev_hmr/hmr-02.main-body.js```

**Comment by swashcap** [comment]
I believe this is due to not running `fyn run bootstrap` in the project root, but bootstrapping is error-ing. 🤔

**Comment by jchip** [comment]
yes, you need to run bootstrap at the top of the project to build all the packages that poc-subapp depends on, https://github.com/electrode-io/electrode/blob/master/CONTRIBUTING.md#getting-started

**Comment by jchip** [comment]
it's mainly the `subapp-*` packages that have a build step, using babel to transpile ES6 code for the browser and node.js.

**Comment by swashcap** [comment]
When running `fyn run bootstrap` I get this error:

```shell
$ fyn run bootstrap
info lifecycle electrode@1.0.0~bootstrap: electrode@1.0.0

> electrode@1.0.0 bootstrap /Users/dudeman/electrode-io/electrode
> fynpo

> Done bootstrap opt-archetype-check fyn -q d install exit code 0
> Done bootstrap electrode-node-resolver fyn -q d install exit code 0
> Done bootstrap subapp-util fyn -q d install exit code 0
> Done bootstrap webpack-config-composer fyn -q d install exit code 0
> Done bootstrap @xarc/create-app fyn -q d install exit code 0
> Done bootstrap electrode-auto-ssr fyn -q d install exit code 0
> Done bootstrap electrode-cookies fyn -q d install exit code 0
> Done bootstrap ignite-core fyn -q d install exit code 0
> Done bootstrap generator-electrode fyn -q d install exit code 0
> Done bootstrap electrode-react-context fyn -q d install exit code 0
> Done bootstrap subapp-pkg-util fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-critical-css fyn -q d install exit code 0
> Done bootstrap electrode-redux-router-engine fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-eslint fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-flow fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-inferno fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-jest fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-karma fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-less fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-mocha fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-phantomjs fyn -q d install exit code 0
> Done bootstrap electrode-ui-config fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-postcss fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-preact fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-react fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-react-intl fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-pwa fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-sinon fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-sass fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-stylus fyn -q d install exit code 0
> Done bootstrap electrode-archetype-opt-typescript fyn -q d install exit code 0
> Done bootstrap electrode-archetype-webpack-dll-dev fyn -q d install exit code 0
> Done bootstrap electrode-ignite fyn -q d install exit code 0
> Done bootstrap electrode-ui-logger fyn -q d install exit code 0
> Done bootstrap electrode-archetype-react-app fyn -q d install exit code 0
> Done bootstrap subapp-web fyn -q d install && npm run build exit code 0
> Done bootstrap electrode-archetype-react-component fyn -q d install exit code 0
> Done bootstrap electrode-react-webapp fyn -q d install exit code 0
> Done bootstrap electrode-archetype-webpack-dll fyn -q d install exit code 0
> Done bootstrap subapp-pbundle fyn -q d install && npm run build exit code 0
> Done bootstrap subapp-react fyn -q d install && npm run build exit code 0
> Done bootstrap subapp-redux fyn -q d install && npm run build exit code 0
> Done bootstrap electrode-archetype-react-component-dev fyn -q d install exit code 0
> Done bootstrap subapp-server fyn -q d install exit code 0
> Done bootstrap electrode-archetype-react-app-dev fyn -q d install failed shell cmd 'fyn -q d install' exit code ERR_CHILD_PROCESS_STDIO_MAXBUFFER
>>> Start of output from bootstrap electrode-archetype-react-app-dev fyn -q d install === 
# ...
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER' }
> Please check the file fynpo-debug.log for more info.
info lifecycle electrode@1.0.0~bootstrap: Failed to exec bootstrap script
```

I've tried this command a few times. Any recommendations?

**Comment by swashcap** [comment]
Also noticed that `fyn` is leaking my npm token to the console:

```
$ fyn run bootstrap
# ...
> Loaded .npmrc ini RC /Users/creed/.npmrc {"progress":false,"cache-min":"60","//registry.npmjs.org/:_authToken":"MY_SECRETS","//npm.pkg.github.com/:_authToken":"MY_SECRETS"}
# ...
```

That seems…not great.

**Comment by jchip** [comment]
- npm token fixed in fyn
- published a new visual-exec that increased exec stdout buffer to 10MB.  It's a downstream dep, but a fresh install should get the the latest.
- please ping me directly if you still run into issues.

**Comment by swashcap** [comment]
Thanks for the version bump. Still seeing this error:

```shell
$ fyn --version
0.2.36
$ fyn run bootstrap
# ...
> Done bootstrap electrode-archetype-react-component-dev fyn -q d install exit code 0
> Done bootstrap subapp-server fyn -q d install exit code 0
> Done bootstrap electrode-archetype-react-app-dev fyn -q d install failed shell cmd 'fyn -q d install' exit code ERR_CHILD_PROCESS_STDIO_MAXBUFFER
>>> Start of output from bootstrap electrode-archetype-react-app-dev fyn -q d install === 
> Loaded .npmrc ini RC /Users/dudeman/.npmrc {"progress":false,"cache-min":"60"}
# ...
     stderr: '' },
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER' }
> Please check the file fynpo-debug.log for more info.
info lifecycle electrode@1.0.0~bootstrap: Failed to exec bootstrap script
```

I'll ping you directly over the next few days.

**Comment by swashcap** [comment]
I upgraded to Node.js 12.14.1 and ran the following:

```shell
npm run cache clean -f && rm -rf `~/.fyn && git clean -fdx
```

Then I re-installed and re-ran bootstrap. Seems to work! 🎉
